apiVersion: v1
kind: Service
metadata:
  name: gestion-taches-frontend
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  selector:
    app: gestion-taches-frontend
